INSERT INTO resources (users_id, thumbnail_path, url, title, description,                                   category, rating) VALUES
(1, '/public/images/thumbs/khanacademy.jpg' ,'https://khanacademy.org', 'Khan Academy', 'Free online educational resource',              0,    5),
(2, '/public/images/thumbs/coursera.jpg' ,'https://coursera.org', 'Coursera', 'Online courses from top universities',                 0,    5),
(3, '/public/images/thumbs/edx.jpg' ,'http://edx.org', 'edX', 'Online learning platform',                                       0,    5),
(4, '/public/images/thumbs/udemy.jpg' ,'http://udemy.com', 'Udemy', 'Online courses for all levels',                              0,    5),
(5, '/public/images/thumbs/codecademy.jpg' ,'HTTP://codecademy.com', 'Codecademy', 'Learn to code interactively',                      0,    5),
(6, '/public/images/thumbs/udacity.jpg' ,'http://udacity.com', 'Udacity', 'Nanodegree programs and free courses',                   0,    5),
(7, '/public/images/thumbs/linkedinlearning.jpg' ,'http://lynda.com', 'Lynda', 'Online video tutorials',                                     0,    5),
(8, '/public/images/thumbs/skillshare.jpg' ,'http://skillshare.com', 'Skillshare', 'Online classes and projects',                      0,    5),
(9, '/public/images/thumbs/openculture.jpg' ,'http://openculture.com', 'Open Culture', 'Free online courses',                           0,    5),
(10,'/public/images/thumbs/alison.jpg' , 'http://alison.com', 'Alison', 'Free online courses',                                     0,    5),
(11,'/public/images/thumbs/pluralsight.jpg' , 'http://pluralsight.com', 'Pluralsight', 'Online tech and creative training',             0,    5),
(12,'/public/images/thumbs/tutorialspoint.jpg' , 'http://tutorialspoint.com', 'Tutorials Point', 'Free tutorials for all levels',          0,    5),
(13,'/public/images/thumbs/freecodecamp.jpg' , 'http://freecodecamp.org', 'Free Code Camp', 'Learn to code with free online courses',    0,    5),
(14,'/public/images/thumbs/sololearn.jpg' , 'http://sololearn.com', 'Solo Learn', 'Learn to code for free',                           0,    5),
(15,'/public/images/thumbs/khanacademykids.jpg' , 'http://khanacademykids.org', 'Khan Academy Kids', 'Free educational games and activities',0,   5),
(16,'/public/images/thumbs/gcflearnfree.jpg' , 'http://gcflearnfree.org', 'GCF Learn Free', 'Free tutorials on a variety of topics',     0,    5),
(17,'/public/images/thumbs/codewars.jpg' , 'http://codewars.com', 'Codewars', 'Practice coding challenges',                          0,    5),
(18,'/public/images/thumbs/codeschool.jpg' , 'http://codeschool.com', 'Code School', 'Learn to code by doing',                         0,    5),
(19,'/public/images/thumbs/theodinproject.jpg' , 'http://theodinproject.com', 'The Odin Project', 'Learn web development for free',        0,    5),
(20,'/public/images/thumbs/w3schools.jpg' , 'http://w3schools.com', 'W3 Schools', 'Web development tutorials',                        0,    5);
