INSERT INTO resources (users_id, url, title, description, category, rating, liked) VALUES
(1, 'http://www.khanacademy.org', 'Khan Academy', 'Free online educational resource',              0,    5,      TRUE),
(2, 'http://www.coursera.org', 'Coursera', 'Online courses from top universities',                 0,    5,      TRUE),
(3, 'http://www.edx.org', 'edX', 'Online learning platform',                                       0,    5,      TRUE),
(4, 'http://www.udemy.com', 'Udemy', 'Online courses for all levels',                              0,    5,      TRUE),
(5, 'http://www.codecademy.com', 'Codecademy', 'Learn to code interactively',                      0,    5,      TRUE),
(6, 'http://www.udacity.com', 'Udacity', 'Nanodegree programs and free courses',                   0,    5,      TRUE),
(7, 'http://www.lynda.com', 'Lynda', 'Online video tutorials',                                     0,    5,      TRUE),
(8, 'http://www.skillshare.com', 'Skillshare', 'Online classes and projects',                      0,    5,      TRUE),
(9, 'http://www.openculture.com', 'Open Culture', 'Free online courses',                           0,    5,      TRUE),
(10, 'http://www.alison.com', 'Alison', 'Free online courses',                                     0,    5,      TRUE),
(11, 'http://www.pluralsight.com', 'Pluralsight', 'Online tech and creative training',             0,    5,      TRUE),
(12, 'http://www.tutorialspoint.com', 'Tutorials Point', 'Free tutorials for all levels',          0,    5,      TRUE),
(13, 'http://www.freecodecamp.org', 'Free Code Camp', 'Learn to code with free online courses',    0,    5,      TRUE),
(14, 'http://www.sololearn.com', 'Solo Learn', 'Learn to code for free',                           0,    5,      TRUE),
(15, 'http://www.khanacademykids.org', 'Khan Academy Kids', 'Free educational games and activities',0,   5,      TRUE),
(16, 'http://www.gcflearnfree.org', 'GCF Learn Free', 'Free tutorials on a variety of topics',     0,    5,      TRUE),
(17, 'http://www.codewars.com', 'Codewars', 'Practice coding challenges',                          0,    5,      TRUE),
(18, 'http://www.codeschool.com', 'Code School', 'Learn to code by doing',                         0,    5,      TRUE),
(19, 'http://www.theodinproject.com', 'The Odin Project', 'Learn web development for free',        0,    5,      TRUE),
(20, 'http://www.w3schools.com', 'W3 Schools', 'Web development tutorials',                        0,    5,      TRUE);
