INSERT INTO resources (users_id, url, title, description,                                   type, rating, liked) VALUES
(1, 'www.khanacademy.org', 'Khan Academy', 'Free online educational resource',              0,    5,      TRUE),
(2, 'www.coursera.org', 'Coursera', 'Online courses from top universities',                 0,    5,      TRUE),
(3, 'www.edx.org', 'edX', 'Online learning platform',                                       0,    5,      TRUE),
(4, 'www.udemy.com', 'Udemy', 'Online courses for all levels',                              0,    5,      TRUE),
(5, 'www.codecademy.com', 'Codecademy', 'Learn to code interactively',                      0,    5,      TRUE),
(6, 'www.udacity.com', 'Udacity', 'Nanodegree programs and free courses',                   0,    5,      TRUE),
(7, 'www.lynda.com', 'Lynda', 'Online video tutorials',                                     0,    5,      TRUE),
(8, 'www.skillshare.com', 'Skillshare', 'Online classes and projects',                      0,    5,      TRUE),
(9, 'www.openculture.com', 'Open Culture', 'Free online courses',                           0,    5,      TRUE),
(10, 'www.alison.com', 'Alison', 'Free online courses',                                     0,    5,      TRUE),
(11, 'www.pluralsight.com', 'Pluralsight', 'Online tech and creative training',             0,    5,      TRUE),
(12, 'www.tutorialspoint.com', 'Tutorials Point', 'Free tutorials for all levels',          0,    5,      TRUE),
(13, 'www.freecodecamp.org', 'Free Code Camp', 'Learn to code with free online courses',    0,    5,      TRUE),
(14, 'www.sololearn.com', 'Solo Learn', 'Learn to code for free',                           0,    5,      TRUE),
(15, 'www.khanacademykids.org', 'Khan Academy Kids', 'Free educational games and activities',0,   5,      TRUE),
(16, 'www.gcflearnfree.org', 'GCF Learn Free', 'Free tutorials on a variety of topics',     0,    5,      TRUE),
(17, 'www.codewars.com', 'Codewars', 'Practice coding challenges',                          0,    5,      TRUE),
(18, 'www.codeschool.com', 'Code School', 'Learn to code by doing',                         0,    5,      TRUE),
(19, 'www.theodinproject.com', 'The Odin Project', 'Learn web development for free',        0,    5,      TRUE),
(20, 'www.w3schools.com', 'W3 Schools', 'Web development tutorials',                        0,    5,      TRUE);
