INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was extremely helpful and the information was very concise. Highly recommend');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'I found this resource incredibly useful, it was very easy to understand and was straight to the point.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Such an amazing resource - it answered all of my questions!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very well written resource, I can definitely see why so many people use it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Great resource, perfect for understanding the basics.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'I would highly recommend this resource as it is easy to understand and provides all of the necessary information.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was a big help in understanding the topic.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Perfect resource for getting a better grasp on the subject.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Excellent resource that helped me clarify my doubts.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Did not expect such a wealth of information from this resource, really amazed!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Would consider this resource essential for anyone wanting to learn more about the topic.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Super comprehensive resource, excellent for gaining a deeper understanding.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Absolutely terrific resource, it had absolutely everything I was looking for.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Wonderful resource! It was a great starting point to learning more.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Helped me gain a greater insight into the issue. Highly recommended!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Definitely made the whole process much easier - thanks! ');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Found the resource quite useful, saved me a lot of time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Brilliant resource, lots of useful facts and figures.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Loved how well-organised this resource was!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'A very informative resource that helped me a lot.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very straightforward and clear - great resource!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Highly recommend this resource if youre looking for something easy to follow.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'What an incredible resource - it made a huge difference.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Fantastic resource - it gave me the tools I needed to make my case.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very well done resource with lots of interesting facts.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Using this resource was a game-changer! Highly recommend.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Gave me a comprehensive understanding of the subject. Highly valuable!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Couldnt believe how helpful this resource was - it truly made my day.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Impressive resource - it gave me the knowledge I needed.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Fantastic resource, really wonderful and easy to access.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Awesome resource - Im very pleased with how much I learned.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was extremely comprehensive and user-friendly.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Excellent resource - its great to have a reliable source like this.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Perfect resource - it provided the info I needed in no time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Incredible resource - couldnt be happier with the results.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Used this resource to get a better idea of the matter and it worked out great.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very useful resource, would highly recommend to anyone.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Extremely helpful resource, saved me hours of research.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource made it so much easier to comprehend the topic. Would definitely use again!');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Another great resource, would suggest to anyone looking for information.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very impressive resource, it totally changed the way I understood the subject.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Absolutely brilliant resource, got me up to speed in no time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was like a miracle - it solved all my problems.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Fantastic resource, so easy to follow and incredibly informative.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Probably one of the best resources around, perfect for getting started.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'What an awesome resource - it cleared up so many things for me.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Utterly amazing resource, it answered all my questions instantly.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource is a great tool for anyone wanting to become an expert.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Couldnt have asked for a more helpful resource - it was terrific');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Extremely comprehensive resource, thoroughly enjoyed learning from it');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Terrible resource, nothing was useful and it took too long to figure out what I needed.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very confusing resource, the information did not make sense at all.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Absolutely awful resource, I couldnt find anything useful from it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was poorly written and was just a waste of time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Unhelpful resource, didnt understand much from it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Disappointing resource, information was unclear and outdated.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Such an unorganized resource - it took me ages to find the information I was looking for.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Horrible resource, didnt offer anything of value.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was so hard to follow that I had to throw it away.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Completely useless resource, couldnt find anything worthwhile here.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Found this resource to be completely irrelevant and inaccurate.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Useless resource, didnt help me gain any knowledge.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was so confusing that I didnt get anything out of it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Dreadful resource - the information was wrong and incomplete.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Not worth the time - I had to search through tons of unrelated information.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Terrible resource - all the facts were wrong and outdated.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Awful resource - it hardly provided any useful information.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Very outdated resource, found no value in it whatsoever.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Couldnt make heads or tails of this resource - totally useless.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Wasteful resource, didnt help me understand the topic better.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Useless resource, the information given had no value.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Cluttered resource - not worth the time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Found nothing useful in this resource, could have used a better one.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Terrible resource, could have been much better.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Poorly written resource, felt like I was being given wrong answers.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Pointless resource, absolutely none of the facts were correct.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Did not expect such a ineffective resource, should have gone somewhere else.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Waste of time - didnt find anything helpful here.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Inaccurate resource, would have been better off without it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Abysmal resource, did not learn a single thing from it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Utterly useless resource, nothing of value was given.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Not impressed - the resource was so poorly organized that it was almost impossible to use.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Terrible resource - couldnt understand a single word from it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Got nothing useful from this resource, it was totally irrelevant.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'No point in using this resource - it was a complete waste of time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Absolutely terrible resource - the info was incorrect and misleading.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Appalling resource - the material was outdated and inaccurate.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Had to double-check my work as this resource was so unreliable.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Found nothing of value in this resource - absolutely terrible.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Did not find this resource to be helpful at all, would not recommend.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'What a joke - this resource was so useless that I regret wasting my time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Dont bother with this resource, there is nothing to learn here.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Far from helpful - this resource gave me nothing useful at all.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Absolutely ridiculous resource - the information was incomplete and false.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Would not suggest this resource to anyone, it was a complete waste of time.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'What a disaster - this resource did not provide anything of value.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Horrendous resource, didnt learn anything from it.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Would not recommend this resource to anyone, it was way too complicated.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Dreadful resource, the facts were inaccurate and useless.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Do not bother with this resource, it was incredibly frustrating');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was only okay but it did the job.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was a bit hard to use but good enough.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The information wasnt comprehensive but was satisfactory.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource had some issues but got the job done.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was a little difficult to navigate but nothing major.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was a little outdated, but the information was still useful.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource provided decent information but wasnt very user friendly.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was alright but could be better organized.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'It took me some time to find what I needed, but the resource worked fine.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource had important information but didnt provide a ton of detail.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Not a great resource but it did give me what I needed.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was alright, there were some areas that could use improvement.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource didnt provide much depth but gave a good overview.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was average, but it provided enough for my needs.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was not perfect but still got the job done.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was okay but nothing outstanding.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was a bit lacking in detail but provided enough information.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'There were some issues with this resource, but overall it was functional.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was acceptable but there could be improvements.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was alright but far from perfect.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was okay but not the best out there.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was just average, nothing special.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Overall this resource was acceptable but not amazing.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was passable but nothing great.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was okay but not up to standards.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Nothing extraordinary about this resource, but it was suitable.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was usable');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was passable but not the best.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was adequate but needs some improvements. ');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Not the best resource out there but it served its purpose.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource might not have been the most reliable but was still helpful.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource offered decent content but wasnt the greatest.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource could have been better but met my expectations.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource wasnt perfect but did what I needed it to do.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource wasnt the most organized but still relevant.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was okay but could have been more user friendly.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was mediocre but still provided what I needed.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Resource wasnt the most comprehensive but fit the bill.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was all right but wasnt the most comprehensive.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource seemed a bit dated but still useful.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource could have been improved but did the job.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'Not a bad resource, but needs some improvements.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was alright for what it was intended for.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource did the job but wasnt my first choice.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was sufficient but not great.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'This resource was okay but far from perfect.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was a bit lacking but worked in the end.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource wasnt the greatest but got the job done.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was okay but not the best.');
INSERT INTO comments (users_id, resources_id, comment) VALUES (random() * 19 + 1, random() * 19 + 1, 'The resource was decent but nothing extraordinary.');
