DROP TABLE IF EXISTS resources CASCADE;

CREATE TABLE  resources (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  url VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  type INTEGER NOT NULL DEFAULT 0,
  rating SMALLINT,
  liked BOOLEAN DEFAULT TRUE
);
