DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE  comments (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  resources_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  comment TEXT
);
